version: '3.5'

services:
  database:
    image: postgres:14
    restart: always
    # Optional: Map the container port to a host port to be able to connect with a local db client 
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./database/psql-init/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres_data:/var/lib/postgresql/data/

  jumpballodds:
    build:
      context: ../
      dockerfile: ./docker/jumpballodds/Dockerfile
      target: prod
    restart: always
    depends_on:
      - database
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ../:/home/web/code
    ports:
      - 8000:8000

  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:80
    depends_on:
      - jumpballodds

volumes:
  postgres_data:
  static_volume:
  media_volume:
